config/routes.rb
Rails.application.routes.draw do

  get "/" => "home#index"
  
  get "/search" => "home#search"
  get "/new_search" => "home#new_search"

  get "/signup" => "users#new"
  get "/profile" => "users#profile"

  get "/login" => "sessions#new"
  post "/login" => "sessions#create"
  get "/logout" => "sessions#destroy"

  resources :users

  resources :sessions
  resources :posts
  resources :comments

end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :user
	belongs_to :post
end

app/models/post.rb
class Post < ActiveRecord::Base
	belongs_to :user
	has_many :comments
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :posts
	has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

def current_user 
	@current_user = User.find(session[:user_id])
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	def create
		puts params.inspect
		@comment = Comment.create(params[:comment])
		# >> bc you have post id user id
		@post = @comment.post
		@user = @post.user

		redirect_to post_path(@post.id)
	end

	def new
		@comment = Comment.new
	end

	def show
		@comment = Comment.find(params[:id])
    	@post = @comment.post
    	@user = @comment.user
	end

	def edit
	end

	def update
	end


  	def destroy
  		@comment = Comment.find(params[:id])
    	@post = @comment.post

    	if @comment.destroy
			flash[:notice] = "comment was successfully deleted"
		else
			flash[:alert] = "there was a problem"
		end

    	redirect_to post_path(@post.id)
  	end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index
	end

	def search
	end

	def new_search
		# @users = User.where(email: params[:query])
		@users = User.where(fname: params[:query])
		# redirect_to :search
	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	def index
		@posts = Post.all
	end

	def create
		@post = Post.where(user_id: current_user).create(params[:post])
		@post.user_id = current_user
		redirect_to posts_path
	end

	def new
		@post = Post.new
	end

	def edit
		@post = Post.find(params[:id])
	end

	def update
		@post = Post.find(params[:id])
    	@post.update(params[:post])
    	@user = @post.user

    	redirect_to posts_path
    	# or also to user_path(@post.user_id)
	end

	def destroy
		@post = Post.find(params[:id])
		if @post.destroy
			flash[:notice] = "post was successfully deleted"
		else
			flash[:alert] = "there was a problem"
		end
		redirect_to :back
	end

	def show
		@post = Post.find(params[:id])
		@user = @post.user
  		# @posts = @user.posts
  		# im saying find the post in the db and for that post get all the comments of that post
  		@comment = Comment.new
  		@comments = @post.comments
	end

	private
	def post_params
		params.require(:post).permit(:body, :user_id, :title)
	end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def new
	end

	def create
		@user = User.where(email: params[:user][:email]).first
		if @user && @user.password == params[:user][:password]
			# this line is actually what logs you in:
			session[:user_id] = @user.id
			flash[:notice] = "You have successfully signed in!"
			redirect_to user_path @user
		else
			flash[:alert] = "There was a problem with the login. Please try again"
			redirect_to :back
		end
	end

	def destroy
		session[:user_id] = nil
		flash[:notice] = "You have successfully signed out!"
		redirect_to "/"
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def index
		if session[:user_id] == nil
			flash[:alert] = "Log in first!"
			redirect_to "/"
		else
			@users = User.all
		end
	end

	def create
		@user = User.new(username: params[:user][:username], email: params[:user][:email], password: params[:user][:password])
		if @user.save
			flash[:notice] = "Your account was created successfully. Please log in!"
			redirect_to new_session_path
		else
			flash[:alert] = "There was a problem saving your account."
			redirect_to new_user_path
		end

		# User.create(params[:user])
		# redirect_to new_user_path

		# you can specify which body if you have the same for e.g. comments and posts
		# params[:post][:body]
		# params[:comment][:body]
		# in the html it's post[body]
	end

	def new
		@user = User.new
	end

	def edit
		@user = User.find(params[:id])
		# has the same code as the show bc they both need to load the info first with the get
		# then you update it with update with a post
	end

	def update
		@user = User.find(params[:id])
		@user.update(params[:user]) 
		# it's automatically getting ALL the params for users from your table (fname, lname etc)

		redirect_to user_path(@user.id)
	end

	def destroy
		@user = User.find(params[:id])
		if @user.destroy
			flash[:notice] = "user was successfully deleted"
		else
			flash[:alert] = "there was a problem"
		end
		redirect_to users_path
	end

	def show
		if session[:user_id] == nil
			flash[:alert] = "Log in first!"
			redirect_to "/"
		else
		@user = User.find(params[:id])
		@post = Post.new
		@posts = Post.where(user_id: params[:id])
		end
	end

	def profile
		@user = current_user
		@post = Post.new
		@posts = Post.where(user_id: current_user.id)
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
	# def log_in(user)
	# 	session[:user_id] = user.id
	# end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<div id="homecontainer">
	<%= image_tag 'https://57.media.tumblr.com/d94cf60b9fadc16975bd5c16be7f5092/tumblr_o3bpy3tSU71rrcri6o1_500.gif', class: "home_image" %>
</div>

app/views/home/new_search.html.erb
<% @users.each do |user| %>
<%= user.fname %><br>
<%= user.lname %><br>
<%= user.email %><br>
<%= user.password %><br>
<% end %>

app/views/home/search.html.erb
<%= form_tag("/new_search", method: "get") do %>
<%= label_tag(:query, "Search:") %>
<%= text_field_tag(:query) %>
<%= submit_tag("Submit") %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Microblog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<header>
<h1>COOL BLOG</h1>
 <nav>
 	<ul>
		<% if session[:user_id] %>
	    <li id="homelink"><a href = "/">Home</a></li>
	    <li id="homelink"><a href = "/profile">Profile</a></li>
	    <li id="homelink"><a href = "/users">Users</a></li>
	    <li id="homelink"><a href = "/posts">Posts</a></li>
	    <% else %>
	    <li id="homelink"><a href = "/">Home</a></li>
	    <% end %>
	 	<% if session[:user_id] %> 
	     <li><a href="/logout">Logout</a></li>
	    <% else %>
	     <li><a href="/signup">Sign Up</a></li>
	     <li><a href="/login">Login</a></li>
	    <% end%>
    </ul>
</nav>
</header>
<body>
<% if flash[:notice] %>
	<div class="flash notice">
		<%= flash[:notice] %>
	</div>
<% end %>

<% if flash[:alert] %>
	<div class="flash alert">
		<%= flash[:alert] %>
	</div>
<% end %>

<div class="container">
  
	<%= yield %>
</div>
</body>
</html>

app/views/posts/edit.html.erb
<div id="profile">
	<h1>Edit <%= @post.user.username %>'s Post:</h1>

	<p><%= @post.body %></p>

	<%= form_for @post do |p| %>
	  
	  <p align="center"><%= p.text_area :body, size: "80x20" %></p>

	  <%= p.submit :update %>

	<% end %>
</div>

app/views/posts/index.html.erb
<div id="postlist">

	<p><a class="btn" href="/posts/new">CREATE A NEW POST HERE</a></p>

	<% @posts.reverse.each do |p| %>
	<div id="post_in_list">
		<h1><%= link_to(p.title, post_path(p.id), method: :get) %></h1>
		<!-- <p>User id: <%= p.user_id %></p> -->
		<p><%= p.body %></p>
		<p align="right"><%= p.comments.count %> comments | <%= link_to("add a comment", post_path(p.id), method: :get) %></p>
		<% if session[:user_id] && p.user_id == current_user.id %>

  		<p class="btn"><%= link_to("EDIT POST", edit_post_path(p.id), method: :get) %></p>

  		<p class="btn"><%= link_to("DELETE POST", post_path(p.id), method: :delete) %></p>
		<% end %>

	</div>
	<% end %>

</div>

app/views/posts/new.html.erb
<div class="new_post_outer">

	<div class="post">
		<%= form_for @post do |f| %>
			<%= f.text_field :title, placeholder: "Give it a cool title" %><br><br>
			<%= f.text_area :body, placeholder: "Write your content here", size: "24x15", class: "textarea" %><br><br>
			<%= f.submit :create, value: "HIT IT!", class: "btn" %>
		<% end %>
	</div>

</div>

app/views/posts/show.html.erb
<div id="post">
	<h1><%= @post.title %></h1>
	<p align="center">by: <%= @post.user.username %></p>
	<p><%= @post.body %></p>
	<% if session[:user_id] && @post.user_id == current_user.id %>
		<p class="btn"><%= link_to("EDIT POST", post_path(params[:id]), method: :edit) %></p>
		<p class="btn"><%= link_to("DELETE POST", post_path(params[:id]), method: :delete) %></p>
	<% end %>
</div>

<div id="comment_outer">
	<p>comments:</p>
	<div id="comment">
		<% @comments.reverse.each do |c| %>

			<p><%= c.body %></p>
			<p align="right"><%= link_to("DELETE", comment_path(c.id), method: :delete) %></p>
			
		<% end %>
	</div>
</div>

<div id="new_comment_outer">
		<%= form_for @comment do |c| %>
		<%= c.hidden_field :post_id, value: @post.id %>
		<%= c.text_area :body, placeholder: "Comment here", class: "textarea" %><br>
		<%= c.submit :create, value: "comment", class: "btn"  %>
		<% end %>
</div>

app/views/users/edit.html.erb
<div id="profile">
<%= form_for @user do |f| %>
	<%= f.text_field :username, placeholder: "username" %><br><br>
	<%= f.email_field :email, placeholder: "email" %><br><br>
	<%= f.password_field :password, placeholder: "password" %><br><br>
	<%= f.text_field :fname, placeholder: "First name" %><br><br>
	<%= f.text_field :lname, placeholder: "Last name" %><br><br>
	<%= f.submit :update %>
<% end %>
</div>

app/views/users/index.html.erb
<div id="profile">
	<h1>COOL USERS</h1>
	<% @users.each do |u| %>
	<div id="post_in_list">
		<h2><%= u.username %></h2>
		<p id="profile_link"><%= link_to("click to view profile", user_path(u.id), method: :get) %></p>
		<p>Email: <%= u.email %></p>
		<p>PICTURE ON THE SIDE</p>
		<!-- right now anyone can delete profiles, but i could add: -->
		<!-- if session[:user_id] && u.id == current_user.id -->
		<p id="profile_link"><%= link_to("DELETE PROFILE", user_path(u.id), method: :delete) %></p>
	</div>
	<% end %>
</div>

app/views/users/new.html.erb
<div id ="profile">
	<h1 align="center">Join us!</h1>
	<h1 align="center">Sign up to start your incredible adventure</h1><br>
	<%= form_for @user do |f| %>
		<%= f.text_field :username, placeholder: "Choose your username" %><br><br>
		<%= f.email_field :email, placeholder: "Type your email address" %><br><br>
		<%= f.password_field :password, placeholder: "Choose a password" %><br><br>
		<%= f.submit :submit %>
	<% end %>
</div>
<!-- text fields for fname and lname moved to edit profile page -->

app/views/users/profile.html.erb
<div id="profile">
	<h1>YOUR PROFILE PAGE</h1>
	<div id="profile_left">
		<%= form_tag("/profile", method: "get") do %>
		<%= text_field "user", "username", placeholder: "username not entered", readonly: true %>
		<%= email_field "user", "email", placeholder: "email not entered", readonly: true %>
		<%= text_field "user", "password", placeholder: "password not entered", readonly: true %>
		<%= text_field "user", "fname", placeholder: "first name not entered", readonly: true %>
		<%= text_field "user", "lname", placeholder: "last name not entered", readonly: true %>
		<% end %>
	</div>

	<div id="profile_right">
		<p align="center">PIC</p>
		<p align="center">WILL GO</p>
		<p align="center">HERE</p>

		<p class="btn"><%= link_to("EDIT PROFILE", edit_user_path(@user.id), method: :get) %></p><br>
		<p class="btn"><%= link_to("DELETE PROFILE", user_path(@user.id), method: :delete) %></p>
	</div>
</div>

<div id="profile_postlist">
	<p><a class="btn" href="/posts/new">CREATE NEW POST</a></p>
	<% @posts.each do |p| %>
	<div id="profile_post">
		<h1 align="center"><%= link_to(p.title, post_path(p.id), method: :get) %></h1>
		<p><%= p.body %></p>
		<p align="right"><%= p.comments.count %> comments | <%= link_to("add a comment", post_path(p.id), method: :get) %></p>
	</div>
	<% end %>
</div>

app/views/users/show.html.erb
<div id="profile">
	<h1><%= @user.username %>'S PROFILE PAGE</h1>
	<% if session[:user_id] && current_user.id == @user.id %>
	<p>email: <%= @user.email %></p>
	<p>pwd: <%= @user.password %></p>
	<% end %>
	<p>first name: <%= @user.fname %></p>
	<p>last name: <%= @user.lname %></p>

<% if session[:user_id] && current_user.id == @user.id %>
	<p class="btn"><%= link_to("EDIT PROFILE", edit_user_path(@user.id), method: :get) %></p>
	<p class="btn"><%= link_to("DELETE PROFILE", user_path(@user.id), method: :delete) %></p>
<% end %>

</div>

<div id="profile_postlist">
	<% @posts.each do |p| %>
	<div id="profile_post">
		<h1 align="center"><%= link_to(p.title, post_path(p.id), method: :get) %></h1>
		<p><%= p.body %></p>
		<p align="right"><%= p.comments.count %> comments | <%= link_to("add a comment", post_path(p.id), method: :get) %></p>
	</div>
	<% end %>
</div>